services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 09db
  api:
    build:
      context: .
    ports:
    - 8080:8080
    depends_on:
      - postgres
